title:             resikcam
email:             mackiser@pm.me
description:       (it's my name spelled backwards)
author:            Mac
baseurl:           ""
url:               "https://res1k.me"

# Social Profiles
twitter_username:  resikcam
github_username:   resikcam
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
