title:             res1k
email:             mackiser@pm.me
description:       A Blog About Video Games (mostly Destiny 2)
author:            res1k
baseurl:           ""
url:               "https://res1k.me"

# Social Profiles
twitter_username:  resikcam
github_username:   res1k
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
